version: '3'

services:
  backend: 
    build: ./backend
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start

  frontend: 
    build: ./frontend
    expose:
      - ${REACT_APP_PROD_PORT}
    ports:
      - ${REACT_APP_PROD_PORT}:${REACT_APP_PROD_PORT}
    links:
      - backend
    command: npm run serve